"""empty message

Revision ID: 190c18813b88
Revises: 51a4a76a2ace
Create Date: 2023-07-08 07:17:37.563134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190c18813b88'
down_revision = '51a4a76a2ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_count', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_count', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
