"""empty message

Revision ID: 51a4a76a2ace
Revises: f7cda72a98c6
Create Date: 2023-07-08 07:14:42.813209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a4a76a2ace'
down_revision = 'f7cda72a98c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_count', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('stock_received', schema=None) as batch_op:
        batch_op.drop_column('is_received')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_received', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('daily_count', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
