"""empty message

Revision ID: a0a3d537f004
Revises: 6826551ec65d
Create Date: 2023-07-06 18:03:30.507682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a3d537f004'
down_revision = '6826551ec65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('shopkeeper')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopkeeper', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
