"""empty message

Revision ID: f7cda72a98c6
Revises: a0a3d537f004
Create Date: 2023-07-07 04:10:35.682648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cda72a98c6'
down_revision = 'a0a3d537f004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_received', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_received', schema=None) as batch_op:
        batch_op.drop_column('is_received')

    # ### end Alembic commands ###
